// Application-wide constants, such as default configurations and data defaults
export const DEFAULT_TOAST_CONFIG = {
    duration: 3000,
};

export const SPECIALTIES = [
    "Anaesthetics",
    "Cardiology",
    "Dermatology",
    "Emergency Medicine",
    "Endocrinology",
    "Family Medicine",
    "Gastroenterology",
    "General Practice",
    "General Surgery",
    "Geriatrics",
    "Haematology",
    "Internal Medicine",
    "Neurology",
    "Obstetrics and Gynaecology",
    "Oncology",
    "Ophthalmology",
    "Orthopaedics",
    "Paediatrics",
    "Psychiatry",
    "Radiology",
    "Respiratory Medicine",
    "Rheumatology",
    "Urology",
];

export const SPECIALTY_SUGGESTIONS: Record<string, string[]> = {
    anaesthetics: [
        "Sugammadex dosing for deep rocuronium block?",
        "Neuraxial anaesthesia timing on DOACs?",
        "TIVA vs volatile for cancer surgery outcomes?",
        "Managing anticipated difficult extubation?",
        "Perioperative GLP-1 agonist aspiration risk?",
        "Intralipid regimen for LAST refractory to standard care?",
        "Anaesthetic considerations in severe pulmonary hypertension?",
        "Regional blocks for rib fractures: erector spinae vs paravertebral?",
        "Perioperative management of pacemakers and ICDs?",
    ],
    cardiology: [
        "SGLT2 inhibitors in HFpEF: current evidence?",
        "DAPT duration after PCI in high bleeding risk?",
        "Early rhythm control in AF: EAST-AFNET implications?",
        "Low-flow low-gradient aortic stenosis workup?",
        "Cardiac sarcoidosis: imaging and immunosuppression?",
        "TAVI vs SAVR in intermediate-risk patients?",
        "Anticoagulation choice in AF with CKD stage 4?",
        "Cardiotoxicity surveillance during anthracyclines and trastuzumab?",
        "ICD indications in non-ischaemic cardiomyopathy post-DANISH?",
    ],
    dermatology: [
        "Biologic selection in psoriasis with comorbid IBD?",
        "JAK inhibitors in atopic dermatitis: positioning and safety?",
        "Managing dupilumab-associated conjunctivitis?",
        "Hidradenitis suppurativa: escalation beyond adalimumab?",
        "Sentinel node biopsy thresholds in melanoma?",
        "Rituximab dosing schedules in pemphigus vulgaris?",
        "Field cancerisation treatment options compared?",
        "Isotretinoin and mental health: current evidence?",
        "Drug-induced bullous pemphigoid: gliptins and beyond?",
    ],
    "emergency medicine": [
        "TXA in trauma: CRASH-3 and head injury subgroups?",
        "Thrombolysis vs thrombectomy in wake-up stroke?",
        "Balanced crystalloids vs saline in sepsis resuscitation?",
        "HEART vs EDACS for chest pain disposition?",
        "Ketamine dosing for agitation: IM vs IV safety?",
        "DOAC-associated ICH: reversal agent selection?",
        "Subsegmental PE: anticoagulate or surveil?",
        "Vasopressor choice in cardiogenic vs septic shock?",
        "Paediatric c-spine clearance: PECARN vs NEXUS?",
    ],
    endocrinology: [
        "GLP-1 vs SGLT2 sequencing in T2DM with CVD?",
        "Adrenal incidentaloma: mild autonomous cortisol secretion workup?",
        "Denosumab discontinuation and rebound fracture risk?",
        "Thyroid nodule molecular testing after indeterminate cytology?",
        "Hypercalcaemia: PTH-independent workup beyond malignancy?",
        "Romosozumab positioning in severe osteoporosis?",
        "Managing thyrotoxicosis in pregnancy: PTU vs carbimazole?",
        "Hybrid closed-loop insulin systems: patient selection?",
        "Primary aldosteronism: when to pursue adrenal vein sampling?",
    ],
    "family medicine": [
        "Deprescribing PPIs: rebound symptoms and tapering?",
        "CKD in T2DM: finerenone alongside SGLT2 inhibitors?",
        "Statin intolerance: rechallenge strategy and alternatives?",
        "Menopausal HRT after WHI reanalysis: risk counselling?",
        "Chronic insomnia: CBT-I access vs pharmacotherapy?",
        "Subclinical hypothyroidism: treat at what TSH?",
        "Lp(a) testing in primary prevention: who and when?",
        "Long COVID: evidence-based management options?",
        "Osteoarthritis: topical vs oral NSAIDs in elderly comorbid patients?",
    ],
    gastroenterology: [
        "Positioning JAK inhibitors vs biologics in ulcerative colitis?",
        "Proactive vs reactive TDM for anti-TNF therapy?",
        "Terlipressin in hepatorenal syndrome: CONFIRM trial impact?",
        "H. pylori eradication after clarithromycin failure?",
        "Endoscopic vs surgical management of Barrett's dysplasia?",
        "TIPS timing in refractory variceal bleeding?",
        "Eosinophilic oesophagitis: dupilumab positioning?",
        "MASLD fibrosis risk stratification: FIB-4 to elastography pathway?",
        "Pouchitis: antibiotics, biologics, and refractory cases?",
    ],
    "general practice": [
        "Deprescribing benzodiazepines in long-term users?",
        "CVD risk tools compared: QRISK3 vs PREVENT?",
        "Antibiotic duration for uncomplicated UTI in men?",
        "GLP-1 agonists for weight management: primary care role?",
        "Perimenopause: distinguishing from thyroid and mood disorders?",
        "PSA discussion in asymptomatic 55-year-old: shared decision points?",
        "Chronic cough workup when first-line empirics fail?",
        "Safe opioid tapering in chronic non-cancer pain?",
        "Managing multimorbidity: prioritising conflicting guidelines?",
    ],
    "general surgery": [
        "Antibiotics-first for uncomplicated appendicitis: CODA trial durability?",
        "Cholecystectomy timing in mild gallstone pancreatitis?",
        "Watch-and-wait after complete response in rectal cancer?",
        "Parastomal hernia: prophylactic mesh evidence?",
        "ERAS protocol components with strongest evidence?",
        "Managing the difficult gallbladder: subtotal cholecystectomy criteria?",
        "Groin hernia in women: laparoscopic approach rationale?",
        "Anastomotic leak risk stratification and prevention?",
        "Perioperative anticoagulation bridging: who still needs it?",
    ],
    geriatrics: [
        "Anticholinergic burden scoring in cognitive decline?",
        "DOAC dosing in frail elderly with fluctuating renal function?",
        "Lecanemab and donanemab: realistic candidacy criteria?",
        "Sarcopenia: screening tools and intervention evidence?",
        "Antihypertensive deprescribing in orthostatic hypotension?",
        "Delirium superimposed on dementia: assessment approach?",
        "Statins in the over-85s: continue or stop?",
        "Fracture liaison: anabolic-first therapy in severe osteoporosis?",
        "Antipsychotics in BPSD: minimising use, managing risk?",
    ],
    haematology: [
        "Bispecific antibodies vs CAR-T sequencing in relapsed myeloma?",
        "VEXAS syndrome: when to suspect and how to confirm?",
        "DOAC failure in antiphospholipid syndrome: management?",
        "Ph-negative MPN: interferon vs hydroxycarbamide first-line?",
        "Measurable residual disease guiding therapy in AML?",
        "Heparin-induced thrombocytopenia: argatroban vs fondaparinux?",
        "TTP: caplacizumab positioning and relapse monitoring?",
        "Iron infusion choice: ferric carboxymaltose hypophosphataemia risk?",
        "Pola-R-CHP vs R-CHOP in DLBCL: applying POLARIX?",
    ],
    "internal medicine": [
        "SIADH: fluid restriction failure, next steps?",
        "Anticoagulating catheter-associated upper limb DVT?",
        "Pre-test probability and PET-CT in PUO workup?",
        "Perioperative medicine consult: RCRI vs newer risk tools?",
        "Refeeding syndrome: phosphate thresholds and prevention?",
        "AKI on CKD: distinguishing contributors and nephrology referral timing?",
        "Corticosteroid taper design after prolonged courses?",
        "Polypharmacy in cirrhosis: safe analgesia options?",
        "IgG4-related disease: recognition and induction therapy?",
    ],
    neurology: [
        "CGRP monoclonals vs gepants: migraine prophylaxis positioning?",
        "High-efficacy early vs escalation in relapsing MS?",
        "Anti-seizure medication choice in women of childbearing age?",
        "Tenecteplase vs alteplase in acute stroke?",
        "Autoimmune encephalitis: antibody panels and empiric immunotherapy?",
        "Parkinson's device-assisted therapy: DBS vs apomorphine vs Duodopa?",
        "Small fibre neuropathy: workup when standard studies normal?",
        "Ocrelizumab and vaccine timing: practical scheduling?",
        "Functional neurological disorder: positive diagnostic signs?",
    ],
    "obstetrics and gynaecology": [
        "Aspirin dosing and timing for pre-eclampsia prevention?",
        "PPH: tranexamic acid timing and uterine tamponade options?",
        "Vaginal birth after two caesareans: counselling points?",
        "Endometriosis: medical suppression vs excision timing?",
        "Metformin vs insulin in gestational diabetes?",
        "Recurrent miscarriage workup: what's actually evidence-based?",
        "PCOS: letrozole first-line ovulation induction evidence?",
        "Managing placenta accreta spectrum: delivery planning?",
        "Progesterone for threatened miscarriage: PRISM applicability?",
    ],
    oncology: [
        "Immunotherapy rechallenge after grade 3 irAE?",
        "ctDNA-guided adjuvant therapy in colorectal cancer?",
        "CDK4/6 inhibitor selection in metastatic breast cancer?",
        "Pembrolizumab in MSI-high tumours: site-agnostic evidence?",
        "Oligometastatic disease: SBRT and local therapy thresholds?",
        "Antibody-drug conjugate sequencing in HER2-low disease?",
        "Steroid-refractory immune colitis: infliximab vs vedolizumab?",
        "Geriatric assessment guiding chemotherapy dose in elderly?",
        "Cachexia: pharmacological options with actual evidence?",
    ],
    ophthalmology: [
        "Faricimab vs aflibercept: extension intervals in nAMD?",
        "MIGS options in mild-moderate glaucoma with cataract?",
        "Geographic atrophy: complement inhibitor real-world value?",
        "Diabetic macular oedema: anti-VEGF non-responders?",
        "Endophthalmitis prophylaxis: intracameral antibiotic evidence?",
        "Progressing myopia in children: atropine and lens options?",
        "GCA: tocilizumab steroid-sparing in ocular involvement?",
        "Herpes zoster ophthalmicus: long-term antiviral suppression?",
        "Corneal cross-linking: timing in progressive keratoconus?",
    ],
    orthopaedics: [
        "Aspirin vs DOAC for VTE prophylaxis after arthroplasty?",
        "Cemented vs uncemented hemiarthroplasty in neck of femur fracture?",
        "Periprosthetic joint infection: DAIR vs staged revision criteria?",
        "Tranexamic acid protocols in elective arthroplasty?",
        "Acute Achilles rupture: operative vs functional bracing?",
        "Distal radius fixation vs cast in the elderly: DRAFFT implications?",
        "Cartilage repair options in the young knee compared?",
        "Robotic-assisted knee arthroplasty: outcome evidence?",
        "Managing metal-on-metal hip surveillance: ion thresholds?",
    ],
    paediatrics: [
        "Febrile infant 29-60 days: sequential biomarker pathways?",
        "Nirsevimab implementation: eligibility and timing?",
        "Paediatric asthma: SMART regimen age thresholds?",
        "Peanut allergy: early introduction and oral immunotherapy status?",
        "PIMS-TS vs Kawasaki: distinguishing features and treatment?",
        "Fluid strategy in DKA post-PECARN?",
        "Constipation refractory to macrogol: escalation options?",
        "ADHD medication choice with comorbid tics or anxiety?",
        "Bronchiolitis high-flow: escalation criteria and weaning?",
    ],
    psychiatry: [
        "Treatment-resistant depression: augmentation vs ketamine vs ECT?",
        "Clozapine rechallenge after neutropenia: risk stratification?",
        "Lithium in renal impairment: continue or switch?",
        "Antipsychotic choice in comorbid metabolic syndrome?",
        "Perinatal prescribing: SSRIs and mood stabilisers by trimester?",
        "Borderline personality disorder: what actually helps in crisis?",
        "PTSD: trauma-focused therapy vs pharmacotherapy sequencing?",
        "Catatonia: lorazepam challenge and ECT thresholds?",
        "Rapid tranquillisation protocols: current evidence base?",
    ],
    radiology: [
        "Incidental pulmonary nodule: Fleischner vs Lung-RADS application?",
        "Gadolinium deposition: agent choice in repeat imaging?",
        "Adrenal incidentaloma: washout CT vs chemical shift MRI?",
        "PI-RADS 3 lesions: biopsy decision factors?",
        "Contrast in eGFR 15-30: current consensus on risk?",
        "CT protocol optimisation for suspected mesenteric ischaemia?",
        "Photon-counting CT: practical advantages so far?",
        "MRI conditional devices: scanning logistics and safety?",
        "Incidental thyroid nodule on CT: reporting thresholds?",
    ],
    "respiratory medicine": [
        "Biologic selection in severe eosinophilic asthma?",
        "Antifibrotics in progressive pulmonary fibrosis beyond IPF?",
        "Triple therapy in COPD: mortality evidence and eosinophil cutoffs?",
        "Ambulatory management of primary spontaneous pneumothorax?",
        "Indwelling pleural catheter vs pleurodesis in malignant effusion?",
        "Bronchiectasis: eradication vs suppression of Pseudomonas?",
        "CTEPH screening after acute PE: who and when?",
        "Home NIV in stable hypercapnic COPD: patient selection?",
        "Lung cancer screening: implementing low-dose CT criteria?",
    ],
    rheumatology: [
        "JAK inhibitor cardiovascular risk: applying ORAL Surveillance?",
        "Difficult-to-treat RA: sequencing after multiple bDMARD failures?",
        "Tocilizumab vs steroid monotherapy relapse rates in GCA?",
        "ANA-negative lupus: when to still pursue the diagnosis?",
        "Methotrexate and MTX-polyglutamate monitoring value?",
        "Axial spondyloarthritis: IL-17 vs TNF inhibitor selection?",
        "Urate-lowering escalation: allopurinol ceiling vs switching?",
        "Interstitial lung disease screening in systemic sclerosis?",
        "Immunosuppression and perioperative timing: hold or continue?",
    ],
    urology: [
        "Active surveillance criteria in intermediate-risk prostate cancer?",
        "PSMA PET positioning in biochemical recurrence?",
        "Medical expulsive therapy: does tamsulosin still have a role?",
        "BCG shortage strategies in non-muscle-invasive bladder cancer?",
        "Aquablation vs HoLEP vs UroLift: selecting BPH intervention?",
        "Recurrent UTI in women: methenamine vs prophylactic antibiotics?",
        "Small renal mass: biopsy, ablation, or surveillance?",
        "Nocturia workup: distinguishing polyuria from storage dysfunction?",
        "Fertility preservation before gonadotoxic therapy: pathways?",
    ],
};
