version: "3"
services:
  test:
    image: localhost/test-scribe:latest
    #build:
    #  context: .
    #  dockerfile: Dockerfile.test
    environment:
      TESTING: true
    volumes:
      - ./server:/usr/src/app/server
      - ./data:/usr/src/app/data
