name: Test and Coverage

on: ["push", "pull_request"]

jobs:
  test:
    name: Test and Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Test Docker Image
        run: docker build -f Dockerfile.test -t phlox-test .

      - name: Create coverage directory
        run: mkdir -p coverage

      - name: Run Tests in Docker Container
        run: |
          docker run --name test-container phlox-test
          docker cp test-container:/usr/src/app/coverage.xml ./coverage/
          docker cp test-container:/usr/src/app/coverage.lcov ./coverage/

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage/coverage.lcov
          format: lcov

      - name: Cleanup
        run: docker rm test-container

  finish:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
