name: Release Please

on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write
    issues: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: google-github-actions/release-please-action@v3
              id: release
              with:
                  release-type: node
                  package-name: Phlox
                  create-release: true
                  changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Maintenance","hidden":true},{"type":"docs","section":"Documentation","hidden":false},{"type":"style","section":"Styling","hidden":true},{"type":"refactor","section":"Code Refactoring","hidden":false},{"type":"perf","section":"Performance Improvements","hidden":false},{"type":"test","section":"Tests","hidden":true}]'

            # Only run the following step if a release was created
            - uses: actions/checkout@v3
              if: ${{ steps.release.outputs.release_created }}
